### ISSUE TITLE
Make ErrorType a typealias instead of protocol?

### ISSUE THREAD

**Issue by gilesvangruisen** [bignerdranch/Result#1]
First off, thanks for the clean and simple implementation of Result. Like you, I'm hoping Apple brings something like this into the standard library but alas; here we are.

I'm using `Result.Failure` with an `NSError` but keep getting the "`NSError` does not conform to protocol `ErrorType`". Not sure how you folks are using this, but perhaps you get the same compiler error.

It looks like `ErrorType` is no more than an empty protocol inheriting from `Printable`. `NSError` does indeed conform to `Printable`, but not `ErrorType`, at least not explicitly. 

Unless you plan to extend the `ErrorType` protocol in the future, this error could be solved by replacing `public protocol ErrorType: Printable …` with `public typealias ErrorType = Printable`

Thoughts? I can pull together a quick PR with this fix if we want to move ahead.

**Comment by jgallagher** [comment]
Sorry for the very long delay! We should've been providing an extension to make `NSError` conform to `ErrorType`; #8 addresses it.
